apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: psql-secrets-manager
  namespace: default
spec:
  refreshInterval: '1m'
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: psql-secrets-manager
    creationPolicy: Owner
  data:
  - secretKey: PASSWORD
    remoteRef:
      key: rds!db-f9228833-07d4-4c90-9763-cf3ce8f6854f
      property: password