apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: psql-secrets-manager
  namespace: default
spec:
  refreshInterval: '1m'
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: psql-secrets-manager
    creationPolicy: Owner
  data:
  - secretKey: PASSWORD
    remoteRef:
      key: rds!db-473f0050-b7ef-4607-b069-515d353c2766
      property: password