apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: psql-secrets-manager
  namespace: default
spec:
  refreshInterval: '30m'
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: psql-secrets-manager
    creationPolicy: Owner
  data:
  - secretKey: PASSWORD
    remoteRef:
      key: rds!db-4f83903c-ce9b-4ce8-9ea7-718f3831213d
      property: password