apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: psql-secrets-manager
  namespace: default
spec:
  refreshInterval: '1m'
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: psql-secrets-manager
    creationPolicy: Owner
  data:
  - secretKey: PASSWORD
    remoteRef:
      key: rds!db-0ebcecb2-799c-4c09-9b84-74aa86678ce4
      property: password